// <auto-generated />
namespace MvcApplication8.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class brendZamena : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(brendZamena));
        
        string IMigrationMetadata.Id
        {
            get { return "201310091804071_brendZamena"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
