// <auto-generated />
namespace MvcApplication8.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class narudzbina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(narudzbina));
        
        string IMigrationMetadata.Id
        {
            get { return "201306192326135_narudzbina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
