// <auto-generated />
namespace MvcApplication8.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migr));
        
        string IMigrationMetadata.Id
        {
            get { return "201310062325207_migr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
