// <auto-generated />
namespace MvcApplication8.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bojaVrednost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bojaVrednost));
        
        string IMigrationMetadata.Id
        {
            get { return "201305221349525_bojaVrednost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
